import { Check2Circle, Bug, ExclamationCircle, InfoCircle, XLg } from 'react-bootstrap-icons';

export const toasts = {
  success: {
    variant: 'success',
    message: 'Success toast',
    topic: 'Success',
    duration: '3',
    horizontalMargin: 0,
    verticalMargin: 0,
    animation: 'smooth',
    position: 'bottom-left',
    backgroundColor: '#06D6A0',
    color: '#FFFFFF',
    id: 1,
    icon: <Check2Circle size={30} />,
    closeIcon: <XLg size={20} />,
  },
  error: {
    variant: 'success',
    message: 'Success toast',
    topic: 'Success',
    duration: '3',
    horizontalMargin: '0',
    verticalMargin: '0',
    animation: 'smooth',
    position: 'bottom-left',
    backgroundColor: '#06D6A0',
    color: '#FFFFFF',
    id: 1,
    backgroundColor: '#E63946',
    color: '#FFFFFF',
    icon: <Bug size={30} />,
    closeIcon: <XLg size={20} />,
  },
  warning: {
    variant: 'warning',
    message: 'Warning toast',
    topic: 'Warning',
    duration: '3',
    horizontalMargin: '0',
    verticalMargin: '0',
    animation: 'smooth',
    position: 'bottom-left',
    backgroundColor: '#06D6A0',
    color: '#FFFFFF',
    id: 1,
    backgroundColor: '#FFBD00',
    color: '#000000',
    icon: <ExclamationCircle size={30} />,
    closeIcon: <XLg size={20} />,
  },
  info: {
    variant: 'success',
    message: 'Success toast',
    topic: 'Success',
    duration: '3',
    horizontalMargin: '0',
    verticalMargin: '0',
    animation: 'smooth',
    position: 'bottom-left',
    backgroundColor: '#06D6A0',
    color: '#FFFFFF',
    id: 1,
    backgroundColor: '#7209B7',
    color: '#FFFFFF',
    icon: <InfoCircle size={30} />,
    closeIcon: <XLg size={20} />,
  },
};
